### PR TITLE
RSpec Testing on enumerable projects.

### PR DESCRIPTION
**Pull request by crappypapa**
In this project, I wrote tests for the following enumerable methods:

- my_each
- my_each_with_index
- my_select
- my_any
- my_all
- my_none
- my_count
- my_map
- my_inject
- multiply_else

### CODE REVIEW

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
------------
Hello @crappypapa You did an amazing job on this project. :clap: 
## TO HIGHLIGHT:
- You have well-structured files.
- You have a great number of tests. 
- Your tests cover positive and negative scenarios.

However, there is a minor change to make to complete this project. :hammer_and_wrench: see it below :point_down: :eyes: 
---------
- [x] Please add on your Readme file how to run the RSpec. Write a step-by-step how to run the tests, think as someone that doesn't know anything about programming. 
-----------------
Make this minor change and send it again for review. :muscle: 
## HAPPY CODING !!!!

**Comment by crappypapa** [comment]
@BrianSammit Thanks for the review. I have added the Rspec instructions as suggested.

**Review by elisha2kyakpo1 — APPROVED** [review]
🎉Congratulations! I'm happy to see you implement all the changes requested.💪

[OPTIONAL] to test code in a file someone should run rspec spec/your_file.rb name, not just rspec. The previous reviewer meant just that not writing all the test cases in your readme.
Happy coding🎉👈✔✔

**Comment by crappypapa** [comment]
@elisha2kyakpo1 Thank you for the tip / clarification.

**Pull request merged**
